### PR TITLE
Fixed "Code Folding" && beautify.js to v1.6.2

### PR DESCRIPTION
**Pull request by iNovozhilov**
I fixed this bug: brackets-beautify#182
I added the code unfolding before replacing.

"Ctrl+A -> Beautify" mode …
If you selected all the text in the file, it is necessary to maintain the same behavior as for all the text (when there is no text selection)

### CODE REVIEW

**Comment by iNovozhilov** [comment]
It will be in the next version?

**Comment by iNovozhilov** [comment]
Update beautify.js to **v1.6.0**.
I tested, bugs not revealed :smile:
Fixed a lot of bugs, including that I was looking forward to: https://github.com/beautify-web/js-beautify/issues/797

**Comment by mak1e** [comment]
Any reason we can't merge this pull request?

**Comment by Hirse** [comment]
I always wanted to have a closer look at this but didn't have the time at first and later forgot about it.

First of all, I don't really understand the bug this is trying to fix.
@mak1e have you been able to reproduce the issue? Can you check that it is in fact solved with this PR?

Secondly it is merging a bugfix with an update of the library which should be handled in seperate PRs.

And thirdly, the updated library is already out of date again, confirming the second point.

**Comment by Hirse** [comment]
Additionally, there is no rush or motivation to work on this currently, as we don't seem to have the possibility to update the Extension in Brackets anyway. See #188

**Comment by iNovozhilov** [comment]
> Secondly it is merging a bugfix with an update of the library which should be handled in seperate PRs.

To separate them at this stage not to turn out. If it is critical will need to re-do the fork and duplicate all changes. And I last time did not work correctly to make merge request from two different branches of the same repository, it led to conflicts.
> translate.yandex.ru

**Comment by iNovozhilov** [comment]
> And thirdly, the updated library is already out of date again, confirming the second point.

This is not a critical problem, update to the latest version can be done after the merger.
I use to install in "brackets" my repository, and periodically check for updates "beautify" on the correction of critical problems for me.
> translate.yandex.ru

**Comment by iNovozhilov** [comment]
For myself, I once again updated beautify.js to v1.6.2.
Waiting for the decision from you, in principle you can divide the merge.
> translate.yandex.ru

**Comment by iNovozhilov** [comment]
divide and conquer

**Pull request closed without merging**
